//! Bundled skills embedded into the binary at compile time.
//!
//! The `build.rs` script collects all `skills/*/SKILL.md` files into
//! `embedded_skills.json`. This module deserializes that blob and provides
//! the raw (name, content) pairs to the skill registry for discovery.

use std::sync::OnceLock;

/// Raw JSON generated by build.rs from `skills/*/SKILL.md`.
const EMBEDDED_SKILLS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/embedded_skills.json"));

#[derive(serde::Deserialize)]
struct EmbeddedSkillEntry {
    name: String,
    content: String,
}

/// Parsed bundled skills cached across calls.
fn parsed_skills() -> &'static Vec<(String, String)> {
    static CACHE: OnceLock<Vec<(String, String)>> = OnceLock::new();
    CACHE.get_or_init(|| {
        let entries: Vec<EmbeddedSkillEntry> = match serde_json::from_str(EMBEDDED_SKILLS_JSON) {
            Ok(v) => v,
            Err(e) => {
                tracing::warn!("Failed to parse embedded skills catalog: {}", e);
                return Vec::new();
            }
        };
        entries.into_iter().map(|e| (e.name, e.content)).collect()
    })
}

/// Load all bundled skill (name, content) pairs compiled into the binary.
///
/// Returns a slice of `(skill_name, skill_md_content)` tuples. These are
/// loaded by the skill registry as the lowest-priority discovery source
/// with `Trusted` trust level (they ship with the application).
pub fn load_bundled_skills() -> &'static [(String, String)] {
    parsed_skills()
}
