//! Provenance tracking for data flow analysis.
//!
//! Every data value can be tagged with its origin. The policy engine uses
//! provenance at effect boundaries to enforce taint-based security rules.
//! Phase 1: types only; enforcement comes in Phase 4.

use serde::{Deserialize, Serialize};

use crate::types::memory::DocId;

/// The origin of a piece of data.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub enum Provenance {
    /// Direct user input.
    User,
    /// System prompt, configuration.
    #[default]
    System,
    /// Result from a capability action.
    ToolOutput { action_name: String },
    /// Generated by the LLM.
    LlmGenerated,
    /// Retrieved from project memory.
    MemoryRetrieval { doc_id: DocId },
}
